// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw83W8MJxKXTU06X9aolW39Tbc1-M8qZA',
    appId: '1:109258134554:web:144f44969464f5303cada3',
    messagingSenderId: '109258134554',
    projectId: 'missing-tanzania-app',
    authDomain: 'missing-tanzania-app.firebaseapp.com',
    storageBucket: 'missing-tanzania-app.firebasestorage.app',
    measurementId: 'G-5ZBQR510Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzuKtqcKDE2lIhEAXk9esOFA-2hKAPiqY',
    appId: '1:109258134554:android:34df77c9741614793cada3',
    messagingSenderId: '109258134554',
    projectId: 'missing-tanzania-app',
    storageBucket: 'missing-tanzania-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXzYyaOTk5osA4NPcNFBU_iTeMWH_wK_4',
    appId: '1:109258134554:ios:bca8cb7fd19dafb53cada3',
    messagingSenderId: '109258134554',
    projectId: 'missing-tanzania-app',
    storageBucket: 'missing-tanzania-app.firebasestorage.app',
    iosBundleId: 'com.example.missingPersonsTz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXzYyaOTk5osA4NPcNFBU_iTeMWH_wK_4',
    appId: '1:109258134554:ios:bca8cb7fd19dafb53cada3',
    messagingSenderId: '109258134554',
    projectId: 'missing-tanzania-app',
    storageBucket: 'missing-tanzania-app.firebasestorage.app',
    iosBundleId: 'com.example.missingPersonsTz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw83W8MJxKXTU06X9aolW39Tbc1-M8qZA',
    appId: '1:109258134554:web:eb8c758e05b173103cada3',
    messagingSenderId: '109258134554',
    projectId: 'missing-tanzania-app',
    authDomain: 'missing-tanzania-app.firebaseapp.com',
    storageBucket: 'missing-tanzania-app.firebasestorage.app',
    measurementId: 'G-EBWZRT5GQG',
  );

}